[tool.bandit]
skips = ["B101"]

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = "C0330,C0326,R0902,R0912"

[tool.pylint.format]
good-names = "i,j,fp"
max-line-length = "88"

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "strict"
